// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import "gorm.io/plugin/soft_delete"

const TableNameUser = "user"

// User 用户
type User struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`              // id
	Account    string                `gorm:"column:account;not null;comment:账号" json:"account"`                         // 账号
	Password   string                `gorm:"column:password;not null;comment:密码" json:"password"`                       // 密码
	UnionID    string                `gorm:"column:union_id;comment:微信开放平台id" json:"union_id"`                          // 微信开放平台id
	MpOpenID   string                `gorm:"column:mp_open_id;comment:公众号openId" json:"mp_open_id"`                     // 公众号openId
	NickName   string                `gorm:"column:nick_name;comment:用户昵称" json:"nick_name"`                            // 用户昵称
	Avatar     string                `gorm:"column:avatar;comment:用户头像" json:"avatar"`                                  // 用户头像
	Profile    string                `gorm:"column:profile;comment:用户简介" json:"profile"`                                // 用户简介
	Role       string                `gorm:"column:role;not null;default:user;comment:用户角色：user/admin/ban" json:"role"` // 用户角色：user/admin/ban
	CreateTime int64                 `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`               // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;not null;comment:更新时间" json:"update_time"`               // 更新时间
	IsDelete   soft_delete.DeletedAt `gorm:"column:is_delete;not null;comment:是否删除;softDelete:flag" json:"is_delete"`   // 是否删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
